////////////////////////////////////////////////////////////////////////////////
//
// Copyright © 2019 by Vault Thirteen.
//
// All rights reserved. No part of this publication may be reproduced,
// distributed, or transmitted in any form or by any means, including
// photocopying, recording, or other electronic or mechanical methods,
// without the prior written permission of the publisher, except in the case
// of brief quotations embodied in critical reviews and certain other
// noncommercial uses permitted by copyright law. For permission requests,
// write to the publisher, addressed “Copyright Protected Material” at the
// address below.
//
////////////////////////////////////////////////////////////////////////////////
//
// Web Site Address:	https://github.com/vault-thirteen.
//
////////////////////////////////////////////////////////////////////////////////

package header

// Mail Message Header Field Names.

// Permanent.
const (
	MailHeaderAcceptLanguage                      = "Accept-Language"                        // [RFC4021]
	MailHeaderAlternateRecipient                  = "Alternate-Recipient"                    // [RFC4021]
	MailHeaderARCAuthenticationResults            = "ARC-Authentication-Results"             // [RFC-ietf-dmarc-arc-protocol-23]
	MailHeaderARCMessageSignature                 = "ARC-Message-Signature"                  // [RFC-ietf-dmarc-arc-protocol-23]
	MailHeaderARCSeal                             = "ARC-Seal"                               // [RFC-ietf-dmarc-arc-protocol-23]
	MailHeaderArchivedAt                          = "Archived-At"                            // [RFC5064]
	MailHeaderAuthenticationResults               = "Authentication-Results"                 // [RFC-ietf-dmarc-rfc7601bis-06]
	MailHeaderAutoSubmitted                       = "Auto-Submitted"                         // [RFC3834 section 5]
	MailHeaderAutoforwarded                       = "Autoforwarded"                          // [RFC4021]
	MailHeaderAutosubmitted                       = "Autosubmitted"                          // [RFC4021]
	MailHeaderBcc                                 = "Bcc"                                    // [RFC5322]
	MailHeaderCc                                  = "Cc"                                     // [RFC5322]
	MailHeaderComments                            = "Comments"                               // [RFC5322]
	MailHeaderContentIdentifier                   = "Content-Identifier"                     // [RFC4021]
	MailHeaderContentReturn                       = "Content-Return"                         // [RFC4021]
	MailHeaderConversion                          = "Conversion"                             // [RFC4021]
	MailHeaderConversionWithLoss                  = "Conversion-With-Loss"                   // [RFC4021]
	MailHeaderDLExpansionHistory                  = "DL-Expansion-History"                   // [RFC4021]
	MailHeaderDate                                = "Date"                                   // [RFC5322]
	MailHeaderDeferredDelivery                    = "Deferred-Delivery"                      // [RFC4021]
	MailHeaderDeliveryDate                        = "Delivery-Date"                          // [RFC4021]
	MailHeaderDiscardedX400IPMSExtensions         = "Discarded-X400-IPMS-Extensions"         // [RFC4021]
	MailHeaderDiscardedX400MTSExtensions          = "Discarded-X400-MTS-Extensions"          // [RFC4021]
	MailHeaderDiscloseRecipients                  = "Disclose-Recipients"                    // [RFC4021]
	MailHeaderDispositionNotificationOptions      = "Disposition-Notification-Options"       // [RFC4021]
	MailHeaderDispositionNotificationTo           = "Disposition-Notification-To"            // [RFC4021]
	MailHeaderDKIMSignature                       = "DKIM-Signature"                         // [RFC6376]
	MailHeaderDowngradedBcc                       = "Downgraded-Bcc"                         // [RFC5504][RFC6857]
	MailHeaderDowngradedCc                        = "Downgraded-Cc"                          // [RFC5504][RFC6857]
	MailHeaderDowngradedDispositionNotificationTo = "Downgraded-Disposition-Notification-To" // [RFC5504][RFC6857]
	MailHeaderDowngradedFinalRecipient            = "Downgraded-Final-Recipient"             // [RFC6857 Section 3.1.10]
	MailHeaderDowngradedFrom                      = "Downgraded-From"                        // [RFC5504][RFC6857 Section 3.1.10]
	MailHeaderDowngradedInReplyTo                 = "Downgraded-In-Reply-To"                 // [RFC6857 Section 3.1.10]
	MailHeaderDowngradedMailFrom                  = "Downgraded-Mail-From"                   // [RFC5504][RFC6857 Section 3.1.10]
	MailHeaderDowngradedMessageId                 = "Downgraded-Message-Id"                  // [RFC6857 Section 3.1.10]
	MailHeaderDowngradedOriginalRecipient         = "Downgraded-Original-Recipient"          // [RFC6857 Section 3.1.10]
	MailHeaderDowngradedRcptTo                    = "Downgraded-Rcpt-To"                     // [RFC5504][RFC6857]
	MailHeaderDowngradedReferences                = "Downgraded-References"                  // [RFC6857 Section 3.1.10]
	MailHeaderDowngradedReplyTo                   = "Downgraded-Reply-To"                    // [RFC5504][RFC6857]
	MailHeaderDowngradedResentBcc                 = "Downgraded-Resent-Bcc"                  // [RFC5504][RFC6857]
	MailHeaderDowngradedResentCc                  = "Downgraded-Resent-Cc"                   // [RFC5504][RFC6857]
	MailHeaderDowngradedResentFrom                = "Downgraded-Resent-From"                 // [RFC5504][RFC6857]
	MailHeaderDowngradedResentReplyTo             = "Downgraded-Resent-Reply-To"             // [RFC5504][RFC6857]
	MailHeaderDowngradedResentSender              = "Downgraded-Resent-Sender"               // [RFC5504][RFC6857]
	MailHeaderDowngradedResentTo                  = "Downgraded-Resent-To"                   // [RFC5504][RFC6857]
	MailHeaderDowngradedReturnPath                = "Downgraded-Return-Path"                 // [RFC5504][RFC6857]
	MailHeaderDowngradedSender                    = "Downgraded-Sender"                      // [RFC5504][RFC6857]
	MailHeaderDowngradedTo                        = "Downgraded-To"                          // [RFC5504][RFC6857]
	MailHeaderEncoding                            = "Encoding"                               // [RFC4021]
	MailHeaderEncrypted                           = "Encrypted"                              // [RFC4021]
	MailHeaderExpires                             = "Expires"                                // [RFC4021]
	MailHeaderExpiryDate                          = "Expiry-Date"                            // [RFC4021]
	MailHeaderFrom                                = "From"                                   // [RFC5322][RFC6854]
	MailHeaderGenerateDeliveryReport              = "Generate-Delivery-Report"               // [RFC4021]
	MailHeaderImportance                          = "Importance"                             // [RFC4021]
	MailHeaderInReplyTo                           = "In-Reply-To"                            // [RFC5322]
	MailHeaderIncompleteCopy                      = "Incomplete-Copy"                        // [RFC4021]
	MailHeaderKeywords                            = "Keywords"                               // [RFC5322]
	MailHeaderLanguage                            = "Language"                               // [RFC4021]
	MailHeaderLatestDeliveryTime                  = "Latest-Delivery-Time"                   // [RFC4021]
	MailHeaderListArchive                         = "List-Archive"                           // [RFC4021]
	MailHeaderListHelp                            = "List-Help"                              // [RFC4021]
	MailHeaderListID                              = "List-ID"                                // [RFC4021]
	MailHeaderListOwner                           = "List-Owner"                             // [RFC4021]
	MailHeaderListPost                            = "List-Post"                              // [RFC4021]
	MailHeaderListSubscribe                       = "List-Subscribe"                         // [RFC4021]
	MailHeaderListUnsubscribe                     = "List-Unsubscribe"                       // [RFC4021]
	MailHeaderListUnsubscribePost                 = "List-Unsubscribe-Post"                  // [RFC8058]
	MailHeaderMessageContext                      = "Message-Context"                        // [RFC4021]
	MailHeaderMessageID                           = "Message-ID"                             // [RFC5322]
	MailHeaderMessageType                         = "Message-Type"                           // [RFC4021]
	MailHeaderMMHSExemptedAddress                 = "MMHS-Exempted-Address"                  // [RFC6477][ACP123 Appendix A1.1 and Appendix B.105]
	MailHeaderMMHSExtendedAuthorisationInfo       = "MMHS-Extended-Authorisation-Info"       // [RFC6477][ACP123 Appendix A1.2 and Appendix B.106]
	MailHeaderMMHSSubjectIndicatorCodes           = "MMHS-Subject-Indicator-Codes"           // [RFC6477][ACP123 Appendix A1.3 and Appendix B.107]
	MailHeaderMMHSHandlingInstructions            = "MMHS-Handling-Instructions"             // [RFC6477][ACP123 Appendix A1.4 and Appendix B.108]
	MailHeaderMMHSMessageInstructions             = "MMHS-Message-Instructions"              // [RFC6477][ACP123 Appendix A1.5 and Appendix B.109]
	MailHeaderMMHSCodressMessageIndicator         = "MMHS-Codress-Message-Indicator"         // [RFC6477][ACP123 Appendix A1.6 and Appendix B.110]
	MailHeaderMMHSOriginatorReference             = "MMHS-Originator-Reference"              // [RFC6477][ACP123 Appendix A1.7 and Appendix B.111]
	MailHeaderMMHSPrimaryPrecedence               = "MMHS-Primary-Precedence"                // [RFC6477][ACP123 Appendix A1.8 and Appendix B.101]
	MailHeaderMMHSCopyPrecedence                  = "MMHS-Copy-Precedence"                   // [RFC6477][ACP123 Appendix A1.9 and Appendix B.102]
	MailHeaderMMHSMessageType                     = "MMHS-Message-Type"                      // [RFC6477][ACP123 Appendix A1.10 and Appendix B.103]
	MailHeaderMMHSOtherRecipientsIndicatorTo      = "MMHS-Other-Recipients-Indicator-To"     // [RFC6477][ACP123 Appendix A1.12 and Appendix B.113]
	MailHeaderMMHSOtherRecipientsIndicatorCC      = "MMHS-Other-Recipients-Indicator-CC"     // [RFC6477][ACP123 Appendix A1.12 and Appendix B.113]
	MailHeaderMMHSAcp127MessageIdentifier         = "MMHS-Acp127-Message-Identifier"         // [RFC6477][ACP123 Appendix A1.14 and Appendix B.116]
	MailHeaderMMHSOriginatorPLAD                  = "MMHS-Originator-PLAD"                   // [RFC6477][ACP123 Appendix A1.15 and Appendix B.117]
	MailHeaderMTPriority                          = "MT-Priority"                            // [RFC6758]
	MailHeaderObsoletes                           = "Obsoletes"                              // [RFC4021]
	MailHeaderOrganization                        = "Organization"                           // [RFC7681]
	MailHeaderOriginalEncodedInformationTypes     = "Original-Encoded-Information-Types"     // [RFC4021]
	MailHeaderOriginalFrom                        = "Original-From"                          // [RFC5703]
	MailHeaderOriginalMessageID                   = "Original-Message-ID"                    // [RFC4021]
	MailHeaderOriginalRecipient                   = "Original-Recipient"                     // [RFC3798][RFC5337]
	MailHeaderOriginatorReturnAddress             = "Originator-Return-Address"              // [RFC4021]
	MailHeaderOriginalSubject                     = "Original-Subject"                       // [RFC5703]
	MailHeaderPICSLabel                           = "PICS-Label"                             // [RFC4021]
	MailHeaderPreventNonDeliveryReport            = "Prevent-NonDelivery-Report"             // [RFC4021]
	MailHeaderPriority                            = "Priority"                               // [RFC4021]
	MailHeaderReceived                            = "Received"                               // [RFC5322][RFC5321]
	MailHeaderReceivedSPF                         = "Received-SPF"                           // [RFC7208]
	MailHeaderReferences                          = "References"                             // [RFC5322]
	MailHeaderReplyBy                             = "Reply-By"                               // [RFC4021]
	MailHeaderReplyTo                             = "Reply-To"                               // [RFC5322]
	MailHeaderRequireRecipientValidSince          = "Require-Recipient-Valid-Since"          // [RFC7293]
	MailHeaderResentBcc                           = "Resent-Bcc"                             // [RFC5322]
	MailHeaderResentCc                            = "Resent-Cc"                              // [RFC5322]
	MailHeaderResentDate                          = "Resent-Date"                            // [RFC5322]
	MailHeaderResentFrom                          = "Resent-From"                            // [RFC5322][RFC6854]
	MailHeaderResentMessageID                     = "Resent-Message-ID"                      // [RFC5322]
	MailHeaderResentReplyTo                       = "Resent-Reply-To"                        // [RFC5322]
	MailHeaderResentSender                        = "Resent-Sender"                          // [RFC5322][RFC6854]
	MailHeaderResentTo                            = "Resent-To"                              // [RFC5322]
	MailHeaderReturnPath                          = "Return-Path"                            // [RFC5322]
	MailHeaderSender                              = "Sender"                                 // [RFC5322][RFC6854]
	MailHeaderSensitivity                         = "Sensitivity"                            // [RFC4021]
	MailHeaderSolicitation                        = "Solicitation"                           // [RFC3865]
	MailHeaderSubject                             = "Subject"                                // [RFC5322]
	MailHeaderSupersedes                          = "Supersedes"                             // [RFC4021]
	MailHeaderTLSReportDomain                     = "TLS-Report-Domain"                      // [RFC8460]
	MailHeaderTLSReportSubmitter                  = "TLS-Report-Submitter"                   // [RFC8460]
	MailHeaderTo                                  = "To"                                     // [RFC5322]
	MailHeaderVBRInfo                             = "VBR-Info"                               // [RFC5518]
	MailHeaderX400ContentIdentifier               = "X400-Content-Identifier"                // [RFC4021]
	MailHeaderX400ContentReturn                   = "X400-Content-Return"                    // [RFC4021]
	MailHeaderX400ContentType                     = "X400-Content-Type"                      // [RFC4021]
	MailHeaderX400MTSIdentifier                   = "X400-MTS-Identifier"                    // [RFC4021]
	MailHeaderX400Originator                      = "X400-Originator"                        // [RFC4021]
	MailHeaderX400Received                        = "X400-Received"                          // [RFC4021]
	MailHeaderX400Recipients                      = "X400-Recipients"                        // [RFC4021]
	MailHeaderX400Trace                           = "X400-Trace"                             // [RFC4021]
)

// Provisional.
const (
	MailHeaderApparentlyTo          = "Apparently-To"            // [RFC2076]
	MailHeaderEDIINTFeatures        = "EDIINT-Features"          // [RFC6017]
	MailHeaderEesstVersion          = "Eesst-Version"            // [RFC7681]
	MailHeaderErrorsTo              = "Errors-To"                // [RFC2076]
	MailHeaderFormSub               = "Form-Sub"                 // [draft-levine-mailbomb-header]
	MailHeaderJabberID              = "Jabber-ID"                // [RFC7259]
	MailHeaderMMHSAuthorizingUsers  = "MMHS-Authorizing-Users"   // [RFC7912]
	MailHeaderPrivicon              = "Privicon"                 // [draft-koenig-privicons]
	MailHeaderSIOLabel              = "SIO-Label"                // [RFC7444]
	MailHeaderSIOLabelHistory       = "SIO-Label-History"        // [RFC7444]
	MailHeaderXArchivedAt           = "X-Archived-At"            // [RFC5064]
	MailHeaderXMittente             = "X-Mittente"               // [RFC6109]
	MailHeaderXRicevuta             = "X-Ricevuta"               // [RFC6109]
	MailHeaderXRiferimentoMessageID = "X-Riferimento-Message-ID" // [RFC6109]
	MailHeaderXTipoRicevuta         = "X-TipoRicevuta"           // [RFC6109]
	MailHeaderXTrasporto            = "X-Trasporto"              // [RFC6109]
	MailHeaderXVerificaSicurezza    = "X-VerificaSicurezza"      // [RFC6109]
)
